// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import * as dotenv from "dotenv";

dotenv.config({ path: path.resolve(process.cwd(), ".env") });

console.log("DIRECT_URL:", process.env.DIRECT_URL); // debug line

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
     seed: "npx tsx src/lib/seed.ts",
  },
  datasource: {
    url: process.env.DIRECT_URL!,
  },
});